---
title: "Customer_Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
#importing libraries
library(flexdashboard)
library(tidyverse)
library(highcharter)
library(htmltools)
library(gt)
library(viridis)
library(flexdashboard)
library(dplyr)
```
```{r}
#importing data
C_seg_data = read.csv(file='customer_segmentation_data_W.csv',header = TRUE,sep = ",")
# Filter the data for females and print out intermediate results
female_data <- C_seg_data %>%
  filter(Gender == "Female")

# Group by Geographic.Information and summarize
female_counts <- female_data %>%
  group_by(Geographic.Information) %>%
  summarise(Count = n())

# Select the top 7 states with the highest number of female workers
top_7_states <- female_counts %>%
  top_n(7, Count) 
# Filter the data for the top 7 states
female_data_top_7 <- female_data %>%
  filter(Geographic.Information %in% top_7_states$Geographic.Information)

# Group by Geographic Information and Marital Status, then count occurrences
marital_status_counts_top_7 <- female_data_top_7 %>%
  group_by(Geographic.Information, Marital.Status) %>%
  summarise(Count = n())

# Filter the data for females
female_data <- C_seg_data %>% 
  filter(Gender == "Female")


# Calculate the count of each marital status
marital_status_counts <- female_data %>% 
  count(Marital.Status)

# Calculate the proportion of each marital status
marital_status_counts <- female_data %>%
  count(Marital.Status) %>%
  mutate(Percentage = prop.table(n) * 100)

# Filter the data for widowed females
widowed_females <- C_seg_data %>%
  filter(Gender == "Female" & Marital.Status == "Widowed")
# Count the occurrences of each education level
education_counts <- count(widowed_females, Education.Level)

```
GRAPHICAL ANALYSIS
=======================================================================

Coloum(.tabset .tabset-fade data-width=650)
-----------------------------------------------------------------------


### No of females working in each geographic location

```{r}
#No of females working in each geographic location
# Create the bar plot
hc <- hchart(female_counts, "column", hcaes(x = Geographic.Information, y = Count)) %>%
  hc_title(text = "Count Of Females Per Location") %>%
  hc_xAxis(labels = list(rotation = 45, align = "right")) %>%
  hc_yAxis(title = list(text = "Count")) %>%
  hc_tooltip(pointFormat = "Count: <b>{point.y}</b>")


hc

```


Column {data-width=350}
-----------------------------------------------------------------------

### Marital Status of females in 7 states with highest female workers 


```{r}
# Create highcharter pie chart object
hc_pie <- hchart(marital_status_counts, "pie", hcaes(x = Marital.Status, y = Percentage)) %>%
  hc_title(text = "Marital Status Distribution of Females") %>%
  hc_tooltip(pointFormat = "Marital Status: <b>{point.name}</b><br/>Percentage: <b>{point.y:.1f}%</b>")

# Display the pie chart
hc_pie

```

### Education Level Distribution of Widowed Females


```{r}

# Create highcharter column chart object
hc_column <- hchart(education_counts, "column", hcaes(x = Education.Level, y = n)) %>%
  hc_title(text = " Education Level of Widowed Female Workers") %>%
  hc_yAxis(title = list(text = "Count")) %>%
  hc_tooltip(pointFormat = "Education Level: <b>{point.name}</b><br/>Count: <b>{point.y}</b>")

# Display the column chart
hc_column

```

